Course Curriculum

INTRODUCTION
 PreviewPublic Intro Video (Release v2) (3:09)
 PreviewScenario - Animals4life (13:28)
 PreviewConnect with other students and your instructor (3:10)
 PreviewCOURSE UPGRADES - SAVE $ WHEN ADDING MORE COURSES
 StartSHARED LESSONS [SHAREDALL] [ASSOCIATESHARED] etc...
 Start🚨 READ ME 🚨 - ENABLE EMAIL UPDATES (IT'S WORTH IT)
COURSE ENVIRONMENT (CREATING AWS ACCOUNTS)
 PreviewAWS Accounts - The Basics (11:33)
 Preview[202511UPDATE] [DEMO] - Creating an AWS Account (5:16)
 PreviewMulti-factor Authentication (MFA) (8:25)
 Preview[202511UPDATE] [DEMO] Adding MFA - General Account Root User (4:47)
 Preview[DOITYOURSELF] Creating the Production Account
 PreviewIdentity and Access Management (IAM) Basics (13:01)
 Preview[202511UPDATE] [DEMO] Creating IAMADMIN user & adding MFA (8:17)
 PreviewIAM Access Keys (7:32)
 Start[DEMO] Creating Access keys and setting up AWS CLI v2 tools (17:43)
Networking and Technical Fundamentals (moved to dedicated course)
 StartTECH FUNDAMENTALS CONTENT (!!PLEASE READ ME!!)
IAM, ACCOUNTS & ORGANIZATIONS
 Start[ASSOCIATESHARED] IAM Identity Policies (15:52)
 Start[ASSOCIATESHARED] IAM Users and ARNs (13:49)
 Start[ASSOCIATESHARED] [DEMO] Simple Identity Permissions in AWS (16:06)
 Start[ASSOCIATESHARED] IAM Groups (7:48)
 Start[ASSOCIATESHARED] [DEMO] Permissions control using IAM Groups (9:24)
 Start[ASSOCIATESHARED] IAM Roles - The Tech (8:13)
 Start[ASSOCIATESHARED] When to use IAM Roles (15:27)
 StartService-linked Roles & PassRole (5:16)
 Start[ASSOCIATESHARED] AWS Organizations (12:56)
 Start[SHAREDALL] [DEMO] AWS Organizations (19:48)
 Start[ASSOCIATESHARED] Service Control Policies (SCP) (12:44)
 Start[SHAREDALL] [DEMO] Using Service Control Policies (16:45)
CLOUDFORMATION
 Start[ASSOCIATESHARED] CloudFormation Physical & Logical Resources (7:30)
 Start[ASSOCIATESHARED] [DEMO] Simple Non Portable Template - PART1 (10:28)
 Start[ASSOCIATESHARED] [DEMO] Simple Non Portable Template - PART2 (11:28)
 Start[ASSOCIATESHARED] CloudFormation Template and Pseudo Parameters (6:53)
 Start[ASSOCIATESHARED] CloudFormation Intrinsic Functions (14:28)
 Start[ASSOCIATESHARED] CloudFormation Mappings (4:30)
 Start[ASSOCIATESHARED] CloudFormation Outputs (3:37)
 Start[ASSOCIATESHARED] [DEMO] Template v2 - Portable (13:34)
 Start[ASSOCIATESHARED] CloudFormation Conditions (7:24)
 Start[ASSOCIATESHARED] CloudFormation DependsOn (7:14)
 Start[ASSOCIATESHARED] CloudFormation Wait Conditions & cfn-signal (11:52)
 Start[ASSOCIATESHARED] CloudFormation Nested Stacks (13:55)
 Start[ASSOCIATESHARED] CloudFormation Cross-Stack References (10:05)
 Start[ASSOCIATESHARED] CloudFormation Stack Sets (9:12)
 Start[ASSOCIATESHARED] CloudFormation Deletion Policy (5:24)
 Start[ASSOCIATESHARED] CloudFormation Stack Roles (6:47)
 Start[ASSOCIATESHARED] CloudFormation Init (CFN-INIT) (8:48)
 Start[ASSOCIATESHARED] CloudFormation cfn-hup (4:13)
 Start[ASSOCIATESHARED] [DEMO] wait conditions, cfnsignal, cfninit and cfnhup-PART1 (12:51)
 Start[ASSOCIATESHARED] [DEMO] wait conditions, cfnsignal, cfninit and cfnhup-PART2 (14:42)
 Start[ASSOCIATESHARED] CloudFormation ChangeSets (11:03)
 Start[ASSOCIATESHARED] CloudFormation Custom Resources (11:03)
 Start[ASSOCIATESHARED] [DEMO] CloudFormation Custom Resources-PART1 (9:12)
 Start[ASSOCIATESHARED] [DEMO] CloudFormation Custom Resources-PART2 (13:27)
 Start[DEMO] CloudFormation Drift Detection (19:38)
ELASTIC BEANSTALK
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Architecture (18:12)
 Start[ASSOCIATESHARED] [DEMO] Elastic Beanstalk (EB) - Application & Environment - PART1 (11:50)
 Start[ASSOCIATESHARED] [DEMO] Elastic Beanstalk (EB) - Add additional environment and config options - PART2 (10:53)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Deployment Policies (11:40)
 Start[ASSOCIATESHARED] [DEMO] Elastic Beanstalk (EB) - Deployment (8:30)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Environments and RDS (4:34)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Advanced Customisation via .ebextensions (4:52)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - HTTPS (1:51)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Cloning (4:44)
 Start[ASSOCIATESHARED] Elastic Beanstalk (EB) - Docker (9:11)
 Start[ASSOCIATESHARED] [DEMO] Elastic Beanstalk (EB) - Section Cleanup (1:40)
LAMBDA, SERVERLESS & APPLICATION SERVICES
 Start[ASSOCIATESHARED] CloudWatchEvents and EventBridge (6:54)
 Start[SHAREDALL] AWS Lambda - PART1 (11:25)
 Start[SHAREDALL] AWS Lambda - PART2 (13:59)
 Start[SHAREDALL] AWS Lambda - PART3 (17:03)
 StartLambda Handler Architecture & Overview - PART1 - Theory (7:52)
 StartLambda Handler Architecture & Overview - PART2 - Walkthrough (10:07)
 Start[DEMO] S3 Events + Lambda (Pixelator) - PART1 (18:03)
 Start[DEMO] S3 Events + Lambda (Pixelator) - PART2 (17:43)
 StartLambda Versions (4:58)
 StartLambda Aliases (4:11)
 Start[DEMO] Aliases and Versions (13:10)
 StartLambda Environment Variables (7:21)
 StartMonitoring & Logging & Tracing Lambda Based Applications (13:24)
 Start[DEMO] Accessing Private VPC Resources using Lambda w/ TheCatAPI!!!! - PART1 (7:53)
 Start[DEMO] Accessing Private VPC Resources using Lambda w/ TheCatAPI!!!! - PART2 (16:19)
 StartLambda Layers (8:29)
 StartLambda Container Images (4:14)
 StartLambda & ALB Integration (5:21)
 StartLambda Resource Policy (9:52)
 Start[SHAREDALL] API Gateway 101 (16:27)
 StartAPI Gateway - Methods and Resources (4:28)
 StartAPI Gateway - Integrations (14:02)
 StartAPI Gateway Stages and Deployments (6:25)
 StartOpen API & Swagger (7:56)
 Start[ASSOCIATESHARED] Simple Notification Service (7:49)
 Start[DOP-C02] [ADVDEMO] API Gateway Integrations - Mock, Lambda, AWS Service (23:55)
 Start[ASSOCIATESHARED] Simple Queue Service (15:30)
 StartSQS Standard vs FIFO Queues (3:29)
 StartSQS Extended Client Library (2:52)
 StartSQS Delay Queues (4:38)
 StartSQS Dead-Letter Queues (4:17)
 Start[ASSOCIATESHARED] Step Functions (16:09)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART1 (5:01)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART2 (8:24)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART3 (12:26)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART4 (12:45)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART5 (13:31)
 Start[MINIPROJECT] Build A Serverless App - Pet-Cuddle-o-Tron - PART6 (2:38)
CONTAINERS, ECR, ECS, EKS
 Start[ASSOCIATESHARED] Introduction to Containers (17:13)
 Start[SHAREDALL] [DEMO] Creating 'container of cats' Docker Image (18:15)
 Start[ASSOCIATESHARED] ECS - Concepts (10:25)
 Start[ASSOCIATESHARED] ECS - Cluster Mode (13:09)
 Start[SHAREDALL] [DEMO] - Deploying 'container of cats' using Fargate [UI UPDATES IN PROGRESS] (13:13)
 Start[SHAREDALL] Kubernetes 101 (11:27)
 Start[SHAREDALL] Elastic Kubernetes Service (EKS) 101 (6:14)
OPSWORKS
 StartOpsWorks - Architecture (15:56)
Credentials and Secrets
 Start[ASSOCIATESHARED] SSM Parameter Store (17:00)
 Start[ASSOCIATESHARED] Secrets Manager (7:47)
Advanced Identity and Permissions
 StartSecurity Token Service (STS) (6:53)
 StartPolicy Interpretation Deep Dive - Example 1 (10:23)
 StartPolicy Interpretation Deep Dive - Example 2 (9:11)
 StartPolicy Interpretation Deep Dive - Example 3 (10:59)
 StartPermissions Boundaries & Use-cases (17:28)
 StartAWS Permissions Evaluation (10:25)
Route53
 PreviewRoute53 Fundamentals (6:29)
 Preview[SHAREDALL] [DEMO] Registering a Domain with route53 (9:49)
 PreviewDNS Record Types (13:25)
 StartR53 Public Hosted Zones (6:28)
 StartR53 Private Hosted Zones (5:10)
 StartCNAME vs R53 Alias (5:19)
 StartSimple Routing (2:17)
 StartR53 Health Checks (12:41)
 StartFailover Routing (1:53)
 Start[SHAREDALL] [DEMO] Using R53 and Failover Routing-PART1 (16:41)
 Start[SHAREDALL] [DEMO] Using R53 and Failover Routing-PART2 (6:28)
 StartMulti Value Routing (2:32)
 StartWeighted Routing (3:24)
 StartLatency Routing (2:44)
 StartGeolocation Routing (5:02)
 StartGeoproximity Routing (4:50)
 StartR53 Interoperability (11:50)
CODE* SUITE - SDLC AUTOMATION
 Start[REFRESHER] CICD in AWS (14:54)
 Start[WALKTHROUGH] Working with a Repo & Pushing to CodeCommit [JUST WATCH, DON'T DO] (11:46)
 Start[REFRESHER] CodePipeline - 101 (4:08)
 Start[REFRESHER] CodeBuild - 101 (6:23)
 Start[REFRESHER] CodeDeploy - 101 (10:21)
 StartElastic Container Registry (ECR) - Architecture (4:14)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE0 - INTRO (2:23)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE1 - CodeCommit (12:31)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE2 - Build a Docker Image w/ CodeBuild - PART1 (13:40)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE2 - Build a Docker Image w/ CodeBuild - PART2 (15:02)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE3 - Joining the dots - pipeline (15:31)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE4 - Deploy our Container w/ CodeDeploy - PART1 (11:29)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE4 - Deploy our Container w/ CodeDeploy - PART2 (7:42)
 Start[DOP-C02] [AdvancedDemo] - CatPipeline - STAGE5 - CLEANUP (4:07)
MONITORING AND LOGGING
 StartCloudWatch - PART1 (9:45)
 StartCloudWatch - PART2 (9:19)
 Start[ASSOCIATESHARED] [DEMO] Logging and Metrics with CloudWatch Agent-PART1 (11:51)
 Start[ASSOCIATESHARED] [DEMO] Logging and Metrics with CloudWatch Agent-PART2 (8:08)
 StartCloudWatch Logs (13:44)
 StartCloudTrail (11:40)
 Start[SHAREDALL] [DEMO] Implementing an Organizational Trail (18:23)
 StartCloudTrail Logfile Integrity (6:28)
DATA ANALYTICS & STREAMING
 Start[ASSOCIATESHARED] Kinesis Data Streams (7:52)
 Start[ASSOCIATESHARED] Kinesis Data Firehose (9:11)
 Start[ASSOCIATESHARED] Kinesis Data Analytics (8:51)
 StartMapReduce 101 (10:24)
 StartEMR Architecture (13:51)
 StartAmazon Redshift (11:32)
 StartAmazon Quicksight (4:08)
 StartAmazon Athena (8:19)
 Start[DEMO] Amazon Athena - PART1 (13:31)
 Start[DEMO] Amazon Athena - PART2 (11:37)
SYSTEMS MANAGER
 StartSSM Architecture and Agent Activation (7:25)
 StartSSM Run Command (4:47)
 StartSSM Documents [NEEDS UPDATE] (7:31)
 StartSSM Inventory & SSM Patching (11:57)
CONFIG & SERVICE CATALOG
 StartAWS Config (6:14)
 StartService Catalog Overview (7:07)
INSPECTOR, TRUSTED ADVISOR & GUARDDUTY
 StartInspector 101 (6:28)
 StartGuardDuty 101 (4:14)
 StartTrusted Advisor 101 (8:54)
STORAGE
 Start[ASSOCIATESHARED] Elastic Block Store (EBS) Service Architecture (8:43)
 Start[ASSOCIATESHARED] EBS Volume Types - General Purpose (9:23)
 Start[ASSOCIATESHARED] EBS Volume Types - Provisioned IOPS (6:15)
 Start[ASSOCIATESHARED] EBS Volume Types - HDD-Based (4:32)
 Start[ASSOCIATESHARED] Instance Store Volumes - Architecture (9:00)
 Start[SHAREDALL] Storage Gateway - Volume Gateway (14:15)
 Start[SHAREDALL] Storage Gateway - Tape Gateway (VTL) (12:11)
 Start[SHAREDALL] Storage Gateway - File Gateway (12:15)
 Start[ASSOCIATESHARED] S3 Security (Resource Policies & ACLs) (18:19)
 Start[ASSOCIATESHARED] S3 Static Hosting (10:36)
 Start[SHAREDALL] [Demo] Creating a static website with S3 (17:55)
 Start[ASSOCIATESHARED] Object Versioning & MFA Delete (7:56)
 Start[SHAREDALL] [DEMO] - S3 Versioning (15:45)
 Start[ASSOCIATESHARED] S3 Performance Optimization (11:42)
 Start[ASSOCIATESHARED] [DEMO] - S3 Performance (5:06)
 Start[ASSOCIATESHARED] Key Management Service (KMS) (18:38)
 Start[SHAREDALL] [DEMO] KMS - Encrypting the battleplans with KMS (12:43)
 Start[SHAREDALL] S3 Object Encryption CSE/SSE (23:31)
 Start[SHAREDALL] [DEMO] Object Encryption and Role Separation (14:50)
 StartS3 Bucket Keys (5:59)
 Start[ASSOCIATESHARED] S3 Object Storage Classes - PART1 (9:23)
 Start[ASSOCIATESHARED] S3 Object Storage Classes - PART2 (11:41)
 Start[ASSOCIATESHARED] S3 Lifecycle Configuration (8:13)
 Start[202304UPDATE] [SHAREDALL] S3 Replication (13:59)
 Start[SHAREDALL] [DEMO] Cross-Region Replication of an S3 Static Website (19:52)
 Start[ASSOCIATESHARED] S3 PreSigned URLs (11:11)
 Start[SHAREDALL] [DEMO] Creating and using PresignedURLs (18:23)
 Start[ASSOCIATESHARED] S3 Select and Glacier Select (5:32)
 StartCross-origin Resource Sharing (CORS) (9:26)
 StartS3 Events (4:32)
 StartS3 Access Logs (3:05)
 StartS3 Object Lock (9:52)
 StartS3 Access Points (5:52)
 StartS3 Inventory (13:54)
 Start[DOP-C02] [ADVDEMO] Multi-Region Access Points (20:25)
 Start[ASSOCIATESHARED] EFS Architecture (9:05)
 Start[ASSOCIATESHARED] FSx for Windows File Server (11:32)
 Start[ASSOCIATESHARED] FSx for Lustre (13:57)
Content Delivery Network (CDN)
 Start[SHAREDALL] CloudFront - Architecture (14:56)
 Start[SHAREDALL] CloudFront (CF) - Behaviours (9:21)
 Start[SHAREDALL] CloudFront - TTL and Invalidations (13:48)
 Start[SHAREDALL] AWS Certificate Manager (ACM) (11:21)
 Start[SHAREDALL] CloudFront - SSL/TLS & SNI (14:59)
 Start[SHAREDALL] CloudFront (CF) - Origin Types & Origin Architecture (10:20)
 Start[SHAREDALL] [DEMO] CloudFront (CF) - Adding a CDN to a static Website-PART1 (16:23)
 Start[SHAREDALL] [DEMO] CloudFront (CF) - Adding a CDN to a static Website-PART2 (12:24)
 Start[SHAREDALL] [DEMO] CloudFront (CF) - Adding an Alternate CNAME and SSL (11:12)
 Start[SHAREDALL] CloudFront - Security - OAI & Custom Origins (8:50)
 Start[SHAREDALL] CloudFront - Private Behaviours, Signed URL & Cookies (7:49)
 Start[SHAREDALL] [DEMO] CloudFront (CF) - Using Origin Access Control (OAC) (new version of OAI) (11:21)
 Start[SHAREDALL] CloudFront - Georestrictions (9:40)
 Start[SHAREDALL] CloudFront - Lambd@Edge (8:03)
DATABASE
 Start[ASSOCIATESHARED] DynamoDB Architecture Basics (10:49)
 Start[ASSOCIATESHARED] DynamoDB Operations, Consistency and Performance - PART1 (13:06)
 Start[ASSOCIATESHARED] DynamoDB Operations, Consistency and Performance - PART2 (11:24)
 Start[ASSOCIATESHARED] DynamoDB Indexes (LSI and GSI) (12:35)
 Start[ASSOCIATESHARED] DynamoDB Streams and Triggers (9:10)
 Start[ASSOCIATESHARED] DynamoDB Accelerator (DAX) (10:58)
 Start[ASSOCIATESHARED] DynamoDB Global Tables (5:09)
 StartDynamoDB Time-To-Live (TTL) (4:49)
HA, FT and DR
 Start[ASSOCIATESHARED] High-Availability vs Fault-Tolerance vs Disaster Recovery (17:21)
 StartTypes of DR - Cold, Warm, PilotLight (17:41)
 StartDR Architecture - Storage (8:09)
 StartDR Architecture - Compute (7:52)
 StartDR Architecture - Database (10:20)
 StartDR Architecture - Networking (8:22)
 StartLaunch Configuration and Templates (4:00)
 StartAuto-Scaling Groups (16:01)
 StartASG Scaling Policies (10:23)
 StartASG Lifecycle Hooks (4:42)
 StartASG Health Checks EC2 vs ALB (3:38)
 Start[REFRESHER] Load Balancing Evolution (4:10)
 Start[SHAREDALL] Elastic Load Balancer Architecture - PART1 (10:18)
 Start[SHAREDALL] Elastic Load Balancer Architecture - PART2 (12:32)
 Start[SHAREDALL] Application Load balancing (ALB) vs Network Load Balancing (NLB) (16:20)
 StartSession State (9:11)
 StartSession Stickiness (9:25)
 Start[SHAREDALL] [DEMO] Seeing Session Stickiness in Action (12:57)
 StartGateway Load Balancer (GWLB) (13:40)
 Start[AdvancedDemo] Architecture Evolution - STAGE1 - PART1 (14:24)
 Start[AdvancedDemo] Architecture Evolution - STAGE1 - PART2 (10:43)
 Start[AdvancedDemo] Architecture Evolution - STAGE2 (12:58)
 Start[AdvancedDemo] Architecture Evolution - STAGE3 (19:30)
 Start[AdvancedDemo] Architecture Evolution - STAGE4 (18:04)
 Start[AdvancedDemo] Architecture Evolution - STAGE 5 - PART1 (11:31)
 Start[AdvancedDemo] Architecture Evolution - STAGE 5 - PART2 (14:56)
 Start[AdvancedDemo] Architecture Evolution - STAGE6 (5:48)
 StartConnection Draining (3:46)
 StartX-Forwarded-For & Proxy Protocol (7:16)
DevOps Security
 Start[DOP-C02] Web Application Firewall (WAF), WEBACLs, Rule Groups and Rules (19:18)
 Start[DOP-C02] AWS Network Firewall - 101 (14:18)
EXAM PREP
 StartSample Question Walkthrough 1 (8:58)
 StartSample Question Walkthrough 2 (8:10)
 StartPractice Exam #1
FINISHING UP
 StartThanks & a favour (3:15)
 StartCOURSE UPGRADES - SAVE $ WHEN ADDING MORE COURSES